
name: Metrics
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 * * * *"}]
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Generate User Metrics
        with:
          # Your GitHub token
          token: ${{ secrets.METRIC }}
          # Options
          user: rudikrudik
          template: classic
          base: header, activity, repositories, community
          config_timezone: Europe/Moscow
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: stars # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0 # Disable limitations
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
      - uses: stalomeow/metrics@edcae0f874d69e509d25ddd5e750a2f41cd54e10
        name: Generate achievements Metrics
        with: 
          filename: images/achievements-metrics.svg
          token: ${{ secrets.METRIC }}
          plugin_achievements: yes
          plugin_achievements_limit: 0
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
